# Launcher ----

#' Create an SSH job launcher object
#'
#' @description
#' An `R6` class that extends `crew::crew_class_launcher` to launch workers
#' on a remote system via SSH.
#'
#' @export
ssh_launcher_class <- R6::R6Class(
  classname = "ssh_launcher_class",
  inherit = crew::crew_class_launcher,
  public = list(
    #' @field ssh_host Passed to [ssh::ssh_connect()]
    ssh_host = NA_character_,
    #' @field ssh_keyfile Passed to [ssh::ssh_connect()]
    ssh_keyfile = NULL,
    #' @field ssh_passwd Passed to [ssh::ssh_connect()]
    ssh_passwd = "",
    #' @field ssh_verbose Passed to [ssh::ssh_connect()]
    ssh_verbose = FALSE,
    #' @field rscript_path Path to `Rscript` on the remote server.
    #'   Defaults to `"Rscript"`, relying on the remote `PATH`.
    rscript_path = "Rscript",
    #' @field remote_log_dir Directory on the remote server where worker
    #'   scripts and log files are written. Defaults to `"/tmp"`.
    remote_log_dir = "/tmp",

    #' @param ... Passed to `crew::crew_class_launcher$initialize()`
    #' @param ssh_host,ssh_keyfile,ssh_passwd,ssh_verbose Passed to
    #'   [ssh::ssh_connect()]
    #' @param rscript_path Path to `Rscript` on the remote server.
    #' @param remote_log_dir Directory on the remote server for worker
    #'   scripts and log files.
    initialize = function(
        ...,
        ssh_host,
        ssh_keyfile    = NULL,
        ssh_passwd     = "",
        ssh_verbose    = FALSE,
        rscript_path   = "Rscript",
        remote_log_dir = "/tmp"
    ) {
      super$initialize(...)
      self$ssh_host       <- ssh_host
      self$ssh_keyfile    <- ssh_keyfile
      self$ssh_passwd     <- ssh_passwd
      self$ssh_verbose    <- ssh_verbose
      self$rscript_path   <- rscript_path
      self$remote_log_dir <- remote_log_dir
    },

    #' @param call Character string with the complete R expression to run
    #'   as a crew worker, as generated by `crew_class_launcher$call()`.
    #' @return A named list with `id`, `pid`, `session`, `remote_script`,
    #'   and `remote_log` identifying the running worker.
    launch_worker = function(call) {
      if (self$ssh_verbose) message("Connecting to: ", self$ssh_host)
      session <- ssh::ssh_connect(
        host    = self$ssh_host,
        keyfile = self$ssh_keyfile,
        passwd  = self$ssh_passwd,
        verbose = self$ssh_verbose
      )
      id            <- crew::crew_random_name()
      remote_script <- paste0(self$remote_log_dir, "/rcrew_worker_", id, ".R")
      remote_log    <- paste0(self$remote_log_dir, "/rcrew_worker_", id, ".log")

      local_script <- tempfile(fileext = ".R")
      on.exit(unlink(local_script), add = TRUE)
      writeLines(call, con = local_script)
      ssh::scp_upload(session, files = local_script, to = remote_script)

      launch_cmd <- sprintf(
        "nohup %s %s > %s 2>&1 & echo $!",
        self$rscript_path, remote_script, remote_log
      )
      if (self$ssh_verbose) message("Running: ", launch_cmd)

      result <- ssh::ssh_exec_internal(session = session, command = launch_cmd)
      if (result$status != 0L) {
        ssh::ssh_disconnect(session)
        stop("Failed to launch remote R worker. stderr:\n", rawToChar(result$stderr))
      }

      pid <- trimws(rawToChar(result$stdout))
      if (!nzchar(pid) || !grepl("^[0-9]+$", pid)) {
        ssh::ssh_disconnect(session)
        stop("Could not determine PID of remote R worker. stdout: ", pid)
      }

      if (self$ssh_verbose) message("Remote worker PID: ", pid)

      private$.ssh_sessions[[id]] <- session
      list(
        id            = id,
        pid           = pid,
        session       = session,
        remote_script = remote_script,
        remote_log    = remote_log
      )
    },

    #' @description
    #' Override the base `terminate()` to explicitly disconnect all SSH
    #' sessions accumulated across `launch_worker()` calls. This ensures
    #' sessions are closed cleanly rather than relying on garbage collection.
    #' @return `NULL` invisibly.
    terminate = function() {
      for (session in private$.ssh_sessions) {
        try(ssh::ssh_disconnect(session), silent = TRUE)
      }
      private$.ssh_sessions <- list()
      super$terminate()
    }
  ),
  private = list(
    # Named list of SSH sessions keyed by worker id, for cleanup in terminate()
    .ssh_sessions = list()
  ),
  cloneable = FALSE
)

# Controller ----

#' Create a controller with the SSH launcher
#'
#' @description
#' Creates an `R6` controller that submits tasks to workers launched on a
#' remote system via SSH. The remote system must be able to reach the local
#' machine on the network — the `host` argument must be set to the local
#' machine's IP address as seen from the remote server (not `"127.0.0.1"`).
#'
#' @param ssh_host Passed to [ssh::ssh_connect()]. Format: `"user@hostname"`
#'   or `"user@hostname:port"`.
#' @param ssh_keyfile Passed to [ssh::ssh_connect()]. Path to SSH private key.
#' @param ssh_passwd Passed to [ssh::ssh_connect()].
#' @param ssh_verbose Passed to [ssh::ssh_connect()].
#' @param rscript_path Path to `Rscript` on the remote server. Defaults to
#'   `"Rscript"`, relying on the remote `PATH`. Override if `Rscript` is not
#'   on the default `PATH`, e.g. `"/usr/local/bin/Rscript"`.
#' @param remote_log_dir Directory on the remote server where worker R scripts
#'   and log files are written. Worker scripts are deleted on termination; log
#'   files are kept for debugging. Defaults to `"/tmp"`.
#' @inheritParams crew::crew_controller_local
#' @export
crew_controller_ssh <- function(
    name           = "ssh controller",
    ssh_host,
    ssh_keyfile    = NULL,
    ssh_passwd     = "",
    ssh_verbose    = FALSE,
    rscript_path   = "Rscript",
    remote_log_dir = "/tmp",
    workers        = 1L,
    host           = NULL,
    port           = NULL,
    tls            = crew::crew_tls(),
    serialization  = NULL,
    profile        = crew::crew_random_name(),
    seconds_interval   = 0.25,
    seconds_timeout    = 60,
    seconds_launch     = 30,
    seconds_idle       = 300,
    seconds_wall       = Inf,
    tasks_max          = Inf,
    tasks_timers       = 0L,
    reset_globals      = TRUE,
    reset_packages     = FALSE,
    reset_options      = FALSE,
    garbage_collection = FALSE,
    r_arguments        = NULL,
    options_metrics    = crew::crew_options_metrics(),
    crashes_max        = 5L,
    backup             = NULL
) {
  client <- crew::crew_client(
    host             = host,
    port             = port,
    tls              = tls,
    serialization    = serialization,
    profile          = profile,
    seconds_interval = seconds_interval,
    seconds_timeout  = seconds_timeout
  )
  launcher <- ssh_launcher_class$new(
    name             = name,
    ssh_host         = ssh_host,
    ssh_keyfile      = ssh_keyfile,
    ssh_passwd       = ssh_passwd,
    ssh_verbose      = ssh_verbose,
    rscript_path     = rscript_path,
    remote_log_dir   = remote_log_dir,
    workers          = workers,
    seconds_interval = seconds_interval,
    seconds_timeout  = seconds_timeout,
    seconds_launch   = seconds_launch,
    seconds_idle     = seconds_idle,
    seconds_wall     = seconds_wall,
    tasks_max        = tasks_max,
    tasks_timers     = tasks_timers,
    tls              = tls,
    r_arguments      = r_arguments,
    options_metrics  = options_metrics
  )
  controller <- crew::crew_controller(
    client             = client,
    launcher           = launcher,
    reset_globals      = reset_globals,
    reset_packages     = reset_packages,
    reset_options      = reset_options,
    garbage_collection = garbage_collection,
    crashes_max        = crashes_max,
    backup             = backup
  )
  controller$validate()
  controller
}
